const ATECO_LABELS: Record<string, string> = {
  '01': 'Agricoltura',
  '02': 'Silvicoltura',
  '03': 'Pesca',
  '05': 'Estrazione carbone',
  '06': 'Estrazione petrolio/gas',
  '10': 'Alimentari',
  '11': 'Bevande',
  '13': 'Tessile',
  '14': 'Abbigliamento',
  '15': 'Pelle e calzature',
  '16': 'Legno',
  '17': 'Carta',
  '18': 'Stampa',
  '20': 'Chimica',
  '21': 'Farmaceutica',
  '22': 'Gomma e plastica',
  '23': 'Minerali non metalliferi',
  '24': 'Metallurgia',
  '25': 'Prodotti in metallo',
  '26': 'Elettronica',
  '27': 'Apparecchiature elettriche',
  '28': 'Macchinari',
  '29': 'Autoveicoli',
  '30': 'Mezzi di trasporto',
  '31': 'Mobili',
  '32': 'Altre manifatturiere',
  '33': 'Riparazione e manutenzione',
  '35': 'Energia',
  '36': 'Acqua',
  '37': 'Gestione rifiuti',
  '38': 'Raccolta rifiuti',
  '41': 'Costruzione edifici',
  '42': 'Ingegneria civile',
  '43': 'Lavori specializzati edilizia',
  '45': 'Commercio autoveicoli',
  '46': 'Commercio ingrosso',
  '47': 'Commercio dettaglio',
  '49': 'Trasporto terrestre',
  '50': 'Trasporto marittimo',
  '51': 'Trasporto aereo',
  '52': 'Magazzinaggio',
  '53': 'Servizi postali',
  '55': 'Alloggio',
  '56': 'Ristorazione',
  '58': 'Editoria',
  '59': 'Cinema e audiovisivi',
  '60': 'Radio e televisione',
  '61': 'Telecomunicazioni',
  '62': 'Software e informatica',
  '63': 'Servizi informativi',
  '64': 'Servizi finanziari',
  '65': 'Assicurazioni',
  '66': 'Attività finanziarie ausiliarie',
  '68': 'Immobiliare',
  '69': 'Legale e contabilità',
  '70': 'Consulenza gestionale',
  '71': 'Architettura e ingegneria',
  '72': 'Ricerca scientifica',
  '73': 'Pubblicità',
  '74': 'Altre attività professionali',
  '75': 'Veterinaria',
  '77': 'Noleggio',
  '78': 'Agenzie per il lavoro',
  '79': 'Agenzie viaggio',
  '80': 'Vigilanza e sicurezza',
  '81': 'Servizi per edifici',
  '82': 'Servizi di supporto',
  '84': 'Pubblica amministrazione',
  '85': 'Istruzione',
  '86': 'Sanità',
  '87': 'Assistenza sociale residenziale',
  '88': 'Assistenza sociale non residenziale',
  '90': 'Arti e spettacolo',
  '91': 'Biblioteche e musei',
  '92': 'Gioco e scommesse',
  '93': 'Sport e intrattenimento',
  '94': 'Associazioni',
  '95': 'Riparazione beni personali',
  '96': 'Altri servizi alla persona',
  '97': 'Datori di lavoro domestico',
  '99': 'Organizzazioni internazionali',
}

export function getAtecoLabel(code: string | undefined | null): string | null {
  if (!code) return null
  const prefix = code.substring(0, 2)
  return ATECO_LABELS[prefix] || null
}

export function formatAteco(code: string | undefined | null): string {
  if (!code) return 'N/D'
  const label = getAtecoLabel(code)
  return label ? `${code} — ${label}` : code
}
